name: thulir
description: "An One Stop Solution to Assist a College Student in every possible way."
publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  encrypt: ^5.0.3
  firebase_messaging: ^15.1.5
  supabase_flutter: ^2.8.1
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  random_avatar: ^0.0.8
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  fl_chart: ^0.69.2
  table_calendar: ^3.1.2
  syncfusion_flutter_charts: ^27.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

